name: Website generation

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.200'
        lfs: true

    - name: Run blog generator
      run: |
        PROD=1 dotnet run
    
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      name: gh-pages publish
      with:
        branch: gh-pages
        folder: out

